DROP TABLE IF EXISTS Bill;  
CREATE TABLE Bill (  
 	BILL_NUMBER BIGINT primary key,
	BILLED_TO varchar2(100),
	BILLED_DATE varchar2(100),
	BILLED_DUE_DATE varchar2(100),
	BILLED_PRICE DECIMAL(20, 2),
	BILLED_TAX DECIMAL(20, 2),
	BILLED_TOTAL DECIMAL(20, 2)  
);  
